sudo: required
language: generic

services:
  - docker

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=artful TRAVIS_DEBIAN_BACKPORTS="artful-security artful-updates" TRAVIS_DEBIAN_INCREMENT_VERSION_NUMBER=true

script:
  - wget -O- https://raw.githubusercontent.com/lamby/travis.debian.net/gh-pages/script.sh | sh -

if:
  tag IS blank
